# Configuration for https://github.com/Royalflamejlh/world-delete-plugin
# List of all worlds that can be deleted
worlds-to-delete:
  # Name of the world folder
  exampleWorld:
    delete-all: false  # Whether to delete all contents of the world folder
    # If delete all is false the following choose which of the worlds folder's to delete
    advancements: true
    data/raids.dat: true # Use a / to delete a specific file within a folder
    datapacks: false
    entities: true
    poi: true
    region: true
    stats: true
    level__dat: true # Replace . with __
    paper-world__yml: false # Replace . with __
    uid__dat: false # Replace . with __

  anotherExampleWorld:
    delete-all: true

  yetAnotherWorld:
    delete-all: false
    advancements: false
    data: true
    datapacks: true
    entities: true
    poi: false
    region: true
    stats: false
    level__dat: false
    paper-world__yml: false
    uid__dat: true